export const API_URL = process.env.API_URL!;
export const PROXY_URL = process.env.PROXY_URL!;
export const WEBSOCKET_URL = process.env.NEXT_PUBLIC_WEBSOCKET_URL!;
export const API_ENDPOINTS = {
  GOOGLE_OAUTH_CALLBACK: "google/oauth/callback/",
  GOOGLE_OAUTH_REDIRECT_URI: "google/oauth/uri/",
  REGISTER: "users/",
  USERS: "users/",
  USER: "users/[id]/",
  USER_BY_USERNAME: "users/by-username/[username]",
  LOGIN: "tokens/",
  PLACES: "places/",
  PLACE_TOGGLE_FAVORITE: "places/[id]/toggle-favorite/",
  PLACE: "places/[id]/",
  AREAS: "areas/",
  AREA: "areas/[id]/",
  REFRESH: "tokens/refresh/",
  TAGS: "tags/",
  FEEDBACKS: "feedbacks/",
  REFERRAL_CODES: "referrals/",
  APPLY_REFERRAL_CODE: "referrals/[code]/apply/",
  COUNTRIES: "countries/",
  CITIES: "cities/",
  SETTINGS: "settings/",
  WEBSOCKET_TOKENS: "ws/tokens/",
  NOTIFICATIONS: "notifications/",
  FILE: "files/[id]/",
  FILES: "files/",
  LANGUAGES: "languages/",
};
